spring.application.name=banking-app

# Database URL - Ensure there are no spaces here
spring.datasource.url=jdbc:mysql://localhost:3306/banking_app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root123

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# This line helps Hibernate understand it is talking to MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
